local Events = {
   ENTITY_COLLIDED = "entity:collided",
   ENTITY_DAMAGED = "entity:damaged",
   ENTITY_DIED = "entity:died",
   ENTITY_HEALTH_CHANGED = "entity:health_changed",
   ENTITY_MANA_CHANGED = "entity:mana_changed",
   ENTITY_HARVESTED = "entity:harvested",
   ENTITY_SPAWNED = "entity:deployed",
   ENTITY_SPAWN_REQUESTED = "entity:spawn_requested",
   ENTITY_INTERACTED = "entity:interacted",
   INPUT_INTERACTED = "input:interacted",
   INPUT_VECTOR_CHANGED = "input:vector_changed",
   INPUT_INVENTORY_OPENED = "input:inventory_opened",
   UI_MODAL_CLOSED = "ui:modal_closed",
   INPUT_INVENTORY_CLICKED = "input:inventory_clicked",
   MACHINE_INTERACTED = "machine:interacted",
   CREATURE_INTERACTED = "creature:interacted",
   PLACEMENT_CLICKED = "placement:clicked",
   PLACEMENT_MODE_ENTERED = "placement_mode:entered",
   PLACEMENT_MODE_EXITED = "placement_mode:exited",
   RITUAL_STARTED = "ritual:started",
   TOOLBAR_SLOT_ACTIVATED = "toolbar:slot_activated",
   WEAPON_ACTIVATED = "weapon:activated",
}

return Events
